//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HS.Message.Share.Attributes;

namespace HS.Message.Model
{


    /// <summary>
    /// MailMessage 条件查询扩展模型
    /// </summary>
    public class MMailMessageCondition:MMailMessage
    {
        /// <summary>
        /// 开始发送时间
        /// </summary>
        [FieldAttribute("开始发送时间")]
        public System.DateTime StartSendTimeStart{ get; set; }
        
        /// <summary>
        /// 开始发送时间
        /// </summary>
        [FieldAttribute("开始发送时间")]
        public System.DateTime StartSendTimeEnd { get; set; }

        /// <summary>
        /// 上一次发送时间
        /// </summary>
        [FieldAttribute("上一次发送时间")]
        public System.DateTime LastSendTimeStart { get; set; }

        /// <summary>
        /// 上一次发送时间
        /// </summary>
        [FieldAttribute("上一次发送时间")]
        public System.DateTime LastSendTimeEnd { get; set; }

        /// <summary>
        /// 下一次发送时间
        /// </summary>
        [FieldAttribute("下一次发送时间")]
        public System.DateTime NextSendTimeStart { get; set; }

        /// <summary>
        /// 下一次发送时间
        /// </summary>
        [FieldAttribute("下一次发送时间")]
        public System.DateTime NextSendTimeEnd { get; set; }

    }
}
