//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HS.Message.Share.Attributes;

namespace HS.Message.Model
{


    /// <summary>
    /// MailSendLogs 条件查询扩展模型
    /// </summary>
    public class MMailSendLogsCondition:MMailSendLogs
    {
        /// <summary>
        /// 发送时间
        /// </summary>
        [FieldAttribute("发送时间")]
        public System.DateTime SendTimeStart { get; set; }

        /// <summary>
        /// 发送时间
        /// </summary>
        [FieldAttribute("发送时间")]
        public System.DateTime SendTimeEnd { get; set; }

    }
}
