//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HS.Message.Share.Attributes;

namespace HS.Message.Model
{


    /// <summary>
    /// SmsMessage 条件查询扩展模型
    /// </summary>
    public class MSmsMessageCondition:MSmsMessage
    {
        /// <summary>
        /// 提交时间;我方提交短信平台时间
        /// </summary>
        [FieldAttribute("提交时间;我方提交短信平台时间")]
        public System.DateTime SubmitTimeStart { get; set; }

        /// <summary>
        /// 提交时间;我方提交短信平台时间
        /// </summary>
        [FieldAttribute("提交时间;我方提交短信平台时间")]
        public System.DateTime SubmitTimeEnd { get; set; }

    }
}
