//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HS.Message.Share.Attributes;

namespace HS.Message.Model
{


    /// <summary>
    /// SmsMessageDetails 条件查询扩展模型
    /// </summary>
    public class MSmsMessageDetailsCondition:MSmsMessageDetails
    {
        /// <summary>
        /// 锁定时间
        /// </summary>
        [FieldAttribute("锁定时间")]
        public System.DateTime LockTimeStart { get; set; }

        /// <summary>
        /// 锁定时间
        /// </summary>
        [FieldAttribute("锁定时间")]
        public System.DateTime LockTimeEnd { get; set; }

        /// <summary>
        /// 提交时间;我方提交短信平台时间
        /// </summary>
        [FieldAttribute("提交时间;我方提交短信平台时间")]
        public System.DateTime SubmitTimeStart { get; set; }

        /// <summary>
        /// 提交时间;我方提交短信平台时间
        /// </summary>
        [FieldAttribute("提交时间;我方提交短信平台时间")]
        public System.DateTime SubmitTimeEnd { get; set; }

        /// <summary>
        /// 接收时间;用户查看时间
        /// </summary>
        [FieldAttribute("接收时间;用户查看时间")]
        public System.DateTime ReceiveTimeStart { get; set; }

        /// <summary>
        /// 接收时间;用户查看时间
        /// </summary>
        [FieldAttribute("接收时间;用户查看时间")]
        public System.DateTime ReceiveTimeEnd { get; set; }

        /// <summary>
        /// 上一次发送时间
        /// </summary>
        [FieldAttribute("上一次发送时间")]
        public System.DateTime LastSendTimeStart { get; set; }

        /// <summary>
        /// 上一次发送时间
        /// </summary>
        [FieldAttribute("上一次发送时间")]
        public System.DateTime LastSendTimeEnd { get; set; }

        /// <summary>
        /// 查询锁定时间
        /// </summary>
        [FieldAttribute("查询锁定时间")]
        public System.DateTime QueryLockTimeStart { get; set; }

        /// <summary>
        /// 查询锁定时间
        /// </summary>
        [FieldAttribute("查询锁定时间")]
        public System.DateTime QueryLockTimeEnd { get; set; }

    }
}
