//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HS.Message.Share.Attributes;

namespace HS.Message.Model
{


    /// <summary>
    /// 邮件模板
    /// </summary>
    public partial class MMailTemplate: MBaseModel
    {
        /// <summary>
        /// 业务类型key
        /// </summary>
        [Field("业务类型key")]
        public string BusinessTypeKey { get; set; }

        /// <summary>
        /// 业务类型value
        /// </summary>
        [Field("业务类型value")]
        public string BusinessTypeValue { get; set; }

        /// <summary>
        /// 模板名称
        /// </summary>
        [Field("模板名称")]
        public string TempName { get; set; }

        /// <summary>
        /// 模板内容;邮件内容模板通过"{key}"来进行模板参数占位
        /// </summary>
        [Field("模板内容")]
        public string TempBody { get; set; }

        /// <summary>
        /// 模板邮件标题;邮件标题模板通过"{key}"来进行模板参数占位
        /// </summary>
        [Field("模板邮件标题")]
        public string TempTitle { get; set; }

        /// <summary>
        /// 状态;1：启用，2：禁用，默认为1
        /// </summary>
        [Field("状态")]
        public int State { get; set; }

    }
}
