//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HS.Message.Share.Attributes;

namespace HS.Message.Model
{


    /// <summary>
    /// 邮件配置-主要存储邮件发送方账号信息
    /// </summary>
    public partial class MMailConfigure: MBaseModel
    {
        /// <summary>
        /// 邮件Smtp服务器
        /// </summary>
        [Field("邮件Smtp服务器")]
        public string SmtpService { get; set; }

        /// <summary>
        /// 发送邮件地址
        /// </summary>
        [Field("发送邮件地址")]
        public string SendEmail { get; set; }

        /// <summary>
        /// 邮件发送密码
        /// </summary>
        [Field("邮件发送密码")]
        public string SendPwd { get; set; }

        /// <summary>
        /// 状态;1：启用，2：禁用，默认为1
        /// </summary>
        [Field("状态")]
        public int State { get; set; }

    }
}
