//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HS.Message.Share.Attributes;

namespace HS.Message.Model
{


    /// <summary>
    /// 邮件消息
    /// </summary>
    public partial class MMailMessage: MBaseModel
    {
        /// <summary>
        /// 消息id
        /// </summary>
        [Field("消息id")]
        public string MessageId { get; set; }

        /// <summary>
        /// 消息接收人id
        /// </summary>
        [Field("消息接收人id")]
        public string ReceiverId { get; set; }

        /// <summary>
        /// 邮件模板id
        /// </summary>
        [Field("邮件模板id")]
        public string MailTemplateId { get; set; }

        /// <summary>
        /// 邮件发送信息配置id
        /// </summary>
        [Field("邮件发送信息配置id")]
        public string MailConfiguerId { get; set; }

        /// <summary>
        /// 邮件标题
        /// </summary>
        [Field("邮件标题")]
        public string MailTitle { get; set; }

        /// <summary>
        /// 邮件内容
        /// </summary>
        [Field("邮件内容")]
        public string MailBody { get; set; }

        /// <summary>
        /// 收件邮箱;支持多个邮件一起发送，不同的接受邮件地址间通过“,”连接起来
        /// </summary>
        [Field("收件邮箱")]
        public string ReceiverEmail { get; set; }

        /// <summary>
        /// 抄送邮箱
        /// </summary>
        [Field("抄送邮箱")]
        public string ReceiverCcEmail { get; set; }

        /// <summary>
        /// 总共发送次数;默认为1一次
        /// </summary>
        [Field("总共发送次数")]
        public int TotalSendNum { get; set; }

        /// <summary>
        /// 发送频率间隔(单位秒);单位为秒，只有要求发送多次的才有效
        /// </summary>
        [Field("发送频率间隔")]
        public int SendFrequency { get; set; }

        /// <summary>
        /// 开始发送时间
        /// </summary>
        [Field("开始发送时间")]
        public DateTime StartSendTime { get; set; }

        /// <summary>
        /// 已经发送次数
        /// </summary>
        [Field("已经发送次数")]
        public int HasSendNum { get; set; }

        /// <summary>
        /// 上一次发送时间
        /// </summary>
        [Field("上一次发送时间")]
        public DateTime LastSendTime { get; set; }

        /// <summary>
        /// 下一次发送时间
        /// </summary>
        [Field("下一次发送时间")]
        public DateTime NextSendTime { get; set; }

        /// <summary>
        /// 发送状态;发送状态：1=待发送，2=已发送，3=发送失败
        /// </summary>
        [Field("发送状态")]
        public int SendState { get; set; }

        /// <summary>
        /// 邮件Smtp服务器
        /// </summary>
        [Field("邮件Smtp服务器")]
        public string SmtpService { get; set; }

        /// <summary>
        /// 发送邮件地址
        /// </summary>
        [Field("发送邮件地址")]
        public string SendEmail { get; set; }

        /// <summary>
        /// 邮件发送密码
        /// </summary>
        [Field("邮件发送密码")]
        public string SendPwd { get; set; }
    }
}
