//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HS.Message.Share.Attributes;

namespace HS.Message.Model
{
    /// <summary>
    /// 邮件发送日志
    /// </summary>
    public partial class MMailSendLogs: MBaseModel
    {
        /// <summary>
        /// 邮件消息Id
        /// </summary>
        [Field("邮件消息Id")]
        public string MailMessageId { get; set; }

        /// <summary>
        /// 邮件标题
        /// </summary>
        [Field("邮件标题")]
        public string MailTitle { get; set; }

        /// <summary>
        /// 邮件内容
        /// </summary>
        [Field("邮件内容")]
        public string MailBody { get; set; }

        /// <summary>
        /// 邮件发送信息配置id
        /// </summary>
        [Field("邮件发送信息配置id")]
        public string MailConfiguerId { get; set; }

        /// <summary>
        /// 收件邮箱;支持多个邮件一起发送，不同的接受邮件地址间通过“,”连接起来
        /// </summary>
        [Field("收件邮箱")]
        public string ReceiverEmail { get; set; }

        /// <summary>
        /// 抄送邮箱
        /// </summary>
        [Field("抄送邮箱")]
        public string ReceiverCcEmail { get; set; }

        /// <summary>
        /// 发送时间
        /// </summary>
        [Field("发送时间")]
        public DateTime SendTime { get; set; }

        /// <summary>
        /// 发送结果状态;1：发送成功，2：发送失败，默认为1
        /// </summary>
        [Field("发送结果状态")]
        public int SendState { get; set; }

        /// <summary>
        /// 发送结果
        /// </summary>
        [Field("发送结果")]
        public string SendResult { get; set; }

    }
}
