//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HS.Message.Share.Attributes;

namespace HS.Message.Model
{


    /// <summary>
    /// 消息接收人
    /// </summary>
    public partial class MMessageReceiver: MBaseModel
    {
        /// <summary>
        /// 消息id
        /// </summary>
        [Field("消息id")]
        public string MessageId { get; set; }

        /// <summary>
        /// 接收人用户id
        /// </summary>
        [Field("接收人用户id")]
        public string ReceiverUserid { get; set; }

        /// <summary>
        /// 接收人姓名
        /// </summary>
        [Field("接收人姓名")]
        public string ReceiverName { get; set; }

        /// <summary>
        /// 邮件
        /// </summary>
        [Field("邮件")]
        public string Email { get; set; }

        /// <summary>
        /// 抄送邮件
        /// </summary>
        [Field("抄送邮件")]
        public string CcEmail { get; set; }

        /// <summary>
        /// 邮件发送状态;1：待发送，2：已发送，3：发送失败
        /// </summary>
        [Field("邮件发送状态")]
        public int? EmailSendState { get; set; }

        /// <summary>
        /// 邮件最近发送时间
        /// </summary>
        [Field("邮件最近发送时间")]
        public DateTime EmailLastSendtime { get; set; }

        /// <summary>
        /// 电话
        /// </summary>
        [Field("电话")]
        public string Phone { get; set; }

        /// <summary>
        /// 短息发送状态;1：待发送，2：已发送，3：发送失败
        /// </summary>
        [Field("短息发送状态")]
        public int? SmsSendState { get; set; }

        /// <summary>
        /// 短息最近发送时间
        /// </summary>
        [Field("短息最近发送时间")]
        public DateTime SmsLastSendtime { get; set; }

        /// <summary>
        /// 企业微信
        /// </summary>
        [Field("企业微信")]
        public string EnterpriseWechat { get; set; }

        /// <summary>
        /// 微信发送状态;1：待发送，2：已发送，3：发送失败
        /// </summary>
        [Field("微信发送状态")]
        public int? WechatSendState { get; set; }

        /// <summary>
        /// 微信最近发送时间
        /// </summary>
        [Field("微信最近发送时间")]
        public DateTime WechatLastSendtime { get; set; }

        /// <summary>
        /// 钉钉
        /// </summary>
        [Field("钉钉")]
        public string Dingtalk { get; set; }

        /// <summary>
        /// 钉钉发送状态;1：待发送，2：已发送，3：发送失败
        /// </summary>
        [Field("钉钉发送状态")]
        public int? DingtalkSendState { get; set; }

        /// <summary>
        /// 钉钉最近发送时间
        /// </summary>
        [Field("钉钉最近发送时间")]
        public DateTime DingtalkLastSendtime { get; set; }

        /// <summary>
        /// 其他消息接收渠道;消息的其他接收渠道，json字符串
        /// </summary>
        [Field("其他消息接收渠道")]
        public string OtherReceiveChannel { get; set; }

        /// <summary>
        /// 其他渠道发送状态;1：待发送，2：已发送，3：发送失败
        /// </summary>
        [Field("其他渠道发送状态")]
        public int? OtherChannelSendState { get; set; }

        /// <summary>
        /// 其他渠道最近发送时间
        /// </summary>
        [Field("其他渠道最近发送时间")]
        public DateTime OtherChannelLastSendtime { get; set; }

    }
}
