//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HS.Message.Share.Attributes;

namespace HS.Message.Model
{


    /// <summary>
    // MessageReceiver数据模型
    /// </summary>
    public partial class MMessageReceiver: MBaseModel
    {
        
        /// <summary>
        // 乐观锁
        /// </summary>
        private int? _REVISION;
        
        /// <summary>
        // id
        /// </summary>
        private int _id;
        
        /// <summary>
        // 逻辑id
        /// </summary>
        private string _logical_id;
        
        /// <summary>
        // 消息id
        /// </summary>
        private string _message_id;
        
        /// <summary>
        // 接收人用户id
        /// </summary>
        private string _receiver_userid;
        
        /// <summary>
        // 接收人姓名
        /// </summary>
        private string _receiver_name;
        
        /// <summary>
        // 邮件
        /// </summary>
        private string _email;
        
        /// <summary>
        // 抄送邮件
        /// </summary>
        private string _cc_email;
        
        /// <summary>
        // 电话
        /// </summary>
        private string _phone;
        
        /// <summary>
        // 企业微信
        /// </summary>
        private string _enterprise_wechat;
        
        /// <summary>
        // 钉钉
        /// </summary>
        private string _dingtalk;
        
        /// <summary>
        // 其他消息接收渠道;消息的其他接收渠道，json字符串
        /// </summary>
        private string _other_receive_channel;
        
        /// <summary>
        // 创建人ID
        /// </summary>
        private string _created_by_id;
        
        /// <summary>
        // 创建人姓名
        /// </summary>
        private string _created_by_name;
        
        /// <summary>
        // 创建时间
        /// </summary>
        private System.DateTime _created_time;
        
        /// <summary>
        // 更新人ID
        /// </summary>
        private string _updated_by_id;
        
        /// <summary>
        // 更新人姓名
        /// </summary>
        private string _updated_by_name;
        
        /// <summary>
        // 更新时间
        /// </summary>
        private System.DateTime _updated_time;
        
        /// <summary>
        /// 乐观锁
        /// </summary>
        [FieldAttribute("乐观锁")]
        public int? REVISION
        {
            get
            {
                return this._REVISION;
            }
            set
            {
                this._REVISION = value;
            }
        }
        
        /// <summary>
        /// id
        /// </summary>
        [FieldAttribute("id")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        /// <summary>
        /// 逻辑id
        /// </summary>
        [FieldAttribute("逻辑id")]
        public string logical_id
        {
            get
            {
                return this._logical_id;
            }
            set
            {
                this._logical_id = value;
            }
        }
        
        /// <summary>
        /// 消息id
        /// </summary>
        [FieldAttribute("消息id")]
        public string message_id
        {
            get
            {
                return this._message_id;
            }
            set
            {
                this._message_id = value;
            }
        }
        
        /// <summary>
        /// 接收人用户id
        /// </summary>
        [FieldAttribute("接收人用户id")]
        public string receiver_userid
        {
            get
            {
                return this._receiver_userid;
            }
            set
            {
                this._receiver_userid = value;
            }
        }
        
        /// <summary>
        /// 接收人姓名
        /// </summary>
        [FieldAttribute("接收人姓名")]
        public string receiver_name
        {
            get
            {
                return this._receiver_name;
            }
            set
            {
                this._receiver_name = value;
            }
        }
        
        /// <summary>
        /// 邮件
        /// </summary>
        [FieldAttribute("邮件")]
        public string email
        {
            get
            {
                return this._email;
            }
            set
            {
                this._email = value;
            }
        }
        
        /// <summary>
        /// 抄送邮件
        /// </summary>
        [FieldAttribute("抄送邮件")]
        public string cc_email
        {
            get
            {
                return this._cc_email;
            }
            set
            {
                this._cc_email = value;
            }
        }
        
        /// <summary>
        /// 电话
        /// </summary>
        [FieldAttribute("电话")]
        public string phone
        {
            get
            {
                return this._phone;
            }
            set
            {
                this._phone = value;
            }
        }
        
        /// <summary>
        /// 企业微信
        /// </summary>
        [FieldAttribute("企业微信")]
        public string enterprise_wechat
        {
            get
            {
                return this._enterprise_wechat;
            }
            set
            {
                this._enterprise_wechat = value;
            }
        }
        
        /// <summary>
        /// 钉钉
        /// </summary>
        [FieldAttribute("钉钉")]
        public string dingtalk
        {
            get
            {
                return this._dingtalk;
            }
            set
            {
                this._dingtalk = value;
            }
        }
        
        /// <summary>
        /// 其他消息接收渠道;消息的其他接收渠道，json字符串
        /// </summary>
        [FieldAttribute("其他消息接收渠道;消息的其他接收渠道，json字符串")]
        public string other_receive_channel
        {
            get
            {
                return this._other_receive_channel;
            }
            set
            {
                this._other_receive_channel = value;
            }
        }
        
        /// <summary>
        /// 创建人ID
        /// </summary>
        [FieldAttribute("创建人ID")]
        public string created_by_id
        {
            get
            {
                return this._created_by_id;
            }
            set
            {
                this._created_by_id = value;
            }
        }
        
        /// <summary>
        /// 创建人姓名
        /// </summary>
        [FieldAttribute("创建人姓名")]
        public string created_by_name
        {
            get
            {
                return this._created_by_name;
            }
            set
            {
                this._created_by_name = value;
            }
        }
        
        /// <summary>
        /// 创建时间
        /// </summary>
        [FieldAttribute("创建时间")]
        public System.DateTime created_time
        {
            get
            {
                return this._created_time;
            }
            set
            {
                this._created_time = value;
            }
        }
        
        /// <summary>
        /// 更新人ID
        /// </summary>
        [FieldAttribute("更新人ID")]
        public string updated_by_id
        {
            get
            {
                return this._updated_by_id;
            }
            set
            {
                this._updated_by_id = value;
            }
        }
        
        /// <summary>
        /// 更新人姓名
        /// </summary>
        [FieldAttribute("更新人姓名")]
        public string updated_by_name
        {
            get
            {
                return this._updated_by_name;
            }
            set
            {
                this._updated_by_name = value;
            }
        }
        
        /// <summary>
        /// 更新时间
        /// </summary>
        [FieldAttribute("更新时间")]
        public System.DateTime updated_time
        {
            get
            {
                return this._updated_time;
            }
            set
            {
                this._updated_time = value;
            }
        }
    }
}
