//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HS.Message.Share.Attributes;

namespace HS.Message.Model
{


    /// <summary>
    // Message数据模型
    /// </summary>
    public partial class MMessage:MBaseModel
    {
        
        /// <summary>
        // 乐观锁
        /// </summary>
        private int? _REVISION;
        
        /// <summary>
        // 主题
        /// </summary>
        private string _title;
        
        /// <summary>
        // 内容
        /// </summary>
        private string _content;
        
        /// <summary>
        // 动态参数;动态参数，用于替换消息模板里面的内容
        /// </summary>
        private string _dynamic_parameter;
        
        /// <summary>
        // 链接地址
        /// </summary>
        private string _link_url;
        
        /// <summary>
        // 链接文本
        /// </summary>
        private string _link_text;
        
        /// <summary>
        // 业务类型key
        /// </summary>
        private string _business_type_key;
        
        /// <summary>
        // 业务类型value
        /// </summary>
        private string _business_type_value;
        
        /// <summary>
        // 消息发送渠道;1:邮件，2:短信，3:企业微信，4:钉钉...... 多个用,隔开
        /// </summary>
        private string _sendchannel;
        
        /// <summary>
        // 创建人ID
        /// </summary>
        private string _created_by_id;
        
        /// <summary>
        // 创建人姓名
        /// </summary>
        private string _created_by_name;
        
        /// <summary>
        // 创建时间
        /// </summary>
        private System.DateTime _created_time;
        
        /// <summary>
        // 更新人ID
        /// </summary>
        private string _updated_by_id;
        
        /// <summary>
        // 更新人姓名
        /// </summary>
        private string _updated_by_name;
        
        /// <summary>
        // 更新时间
        /// </summary>
        private System.DateTime _updated_time;
        
        /// <summary>
        /// 乐观锁
        /// </summary>
        [FieldAttribute("乐观锁")]
        public int? REVISION
        {
            get
            {
                return this._REVISION;
            }
            set
            {
                this._REVISION = value;
            }
        }
        
        /// <summary>
        /// 主题
        /// </summary>
        [FieldAttribute("主题")]
        public string title
        {
            get
            {
                return this._title;
            }
            set
            {
                this._title = value;
            }
        }
        
        /// <summary>
        /// 内容
        /// </summary>
        [FieldAttribute("内容")]
        public string content
        {
            get
            {
                return this._content;
            }
            set
            {
                this._content = value;
            }
        }
        
        /// <summary>
        /// 动态参数;动态参数，用于替换消息模板里面的内容
        /// </summary>
        [FieldAttribute("动态参数;动态参数，用于替换消息模板里面的内容")]
        public string dynamic_parameter
        {
            get
            {
                return this._dynamic_parameter;
            }
            set
            {
                this._dynamic_parameter = value;
            }
        }
        
        /// <summary>
        /// 链接地址
        /// </summary>
        [FieldAttribute("链接地址")]
        public string link_url
        {
            get
            {
                return this._link_url;
            }
            set
            {
                this._link_url = value;
            }
        }
        
        /// <summary>
        /// 链接文本
        /// </summary>
        [FieldAttribute("链接文本")]
        public string link_text
        {
            get
            {
                return this._link_text;
            }
            set
            {
                this._link_text = value;
            }
        }
        
        /// <summary>
        /// 业务类型key
        /// </summary>
        [FieldAttribute("业务类型key")]
        public string business_type_key
        {
            get
            {
                return this._business_type_key;
            }
            set
            {
                this._business_type_key = value;
            }
        }
        
        /// <summary>
        /// 业务类型value
        /// </summary>
        [FieldAttribute("业务类型value")]
        public string business_type_value
        {
            get
            {
                return this._business_type_value;
            }
            set
            {
                this._business_type_value = value;
            }
        }
        
        /// <summary>
        /// 消息发送渠道;1:邮件，2:短信，3:企业微信，4:钉钉...... 多个用,隔开
        /// </summary>
        [FieldAttribute("消息发送渠道;1:邮件，2:短信，3:企业微信，4:钉钉...... 多个用,隔开")]
        public string sendchannel
        {
            get
            {
                return this._sendchannel;
            }
            set
            {
                this._sendchannel = value;
            }
        }
        
        /// <summary>
        /// 创建人ID
        /// </summary>
        [FieldAttribute("创建人ID")]
        public string created_by_id
        {
            get
            {
                return this._created_by_id;
            }
            set
            {
                this._created_by_id = value;
            }
        }
        
        /// <summary>
        /// 创建人姓名
        /// </summary>
        [FieldAttribute("创建人姓名")]
        public string created_by_name
        {
            get
            {
                return this._created_by_name;
            }
            set
            {
                this._created_by_name = value;
            }
        }
        
        /// <summary>
        /// 创建时间
        /// </summary>
        [FieldAttribute("创建时间")]
        public System.DateTime created_time
        {
            get
            {
                return this._created_time;
            }
            set
            {
                this._created_time = value;
            }
        }
        
        /// <summary>
        /// 更新人ID
        /// </summary>
        [FieldAttribute("更新人ID")]
        public string updated_by_id
        {
            get
            {
                return this._updated_by_id;
            }
            set
            {
                this._updated_by_id = value;
            }
        }
        
        /// <summary>
        /// 更新人姓名
        /// </summary>
        [FieldAttribute("更新人姓名")]
        public string updated_by_name
        {
            get
            {
                return this._updated_by_name;
            }
            set
            {
                this._updated_by_name = value;
            }
        }
        
        /// <summary>
        /// 更新时间
        /// </summary>
        [FieldAttribute("更新时间")]
        public System.DateTime updated_time
        {
            get
            {
                return this._updated_time;
            }
            set
            {
                this._updated_time = value;
            }
        }
    }
}
