//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HS.Message.Share.Attributes;

namespace HS.Message.Model
{


    /// <summary>
    /// 短息配置
    /// </summary>
    public partial class MSmsConfigure: MBaseModel
    {
        /// <summary>
        /// 渠道编号;1、阿里云，2、上海大汉三通数据通信
        /// </summary>
        [Field("渠道编号")]
        public int ChannelCode { get; set; }

        /// <summary>
        /// 渠道名称
        /// </summary>
        [Field("渠道名称")]
        public string ChannelName { get; set; }

        /// <summary>
        /// 服务器地址
        /// </summary>
        [Field("服务器地址")]
        public string SmsService { get; set; }

        /// <summary>
        /// 短信发送账号
        /// </summary>
        [Field("短信发送账号")]
        public string SmsAccount { get; set; }

        /// <summary>
        /// 短信发送密码
        /// </summary>
        [Field("短信发送密码")]
        public string SmsPwd { get; set; }

        /// <summary>
        /// 模板编码
        /// </summary>
        [Field("模板编码")]
        public string TemplateCode { get; set; }

        /// <summary>
        /// 签名名称
        /// </summary>
        [Field("签名名称")]
        public string SignName { get; set; }

        /// <summary>
        /// 是否为当前渠道;1：当前渠道，
        /// </summary>
        [Field("是否为当前渠道")]
        public int IsCurrentChannel { get; set; }

        /// <summary>
        /// 状态;1：启用，2：禁用，默认为1
        /// </summary>
        [Field("状态")]
        public int State { get; set; }

    }
}
