//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HS.Message.Share.Attributes;

namespace HS.Message.Model
{


    /// <summary>
    /// 短息消息
    /// </summary>
    public partial class MSmsMessage: MBaseModel
    {
        /// <summary>
        /// 消息id
        /// </summary>
        [Field("消息id")]
        public string MessageId { get; set; }

        /// <summary>
        /// 消息接收人id
        /// </summary>
        [Field("消息接收人id")]
        public string ReceiverId { get; set; }

        /// <summary>
        /// 短息渠道编号;1：阿里云
        /// </summary>
        [Field("短息渠道编号")]
        public int ChannelCode { get; set; }

        /// <summary>
        /// 短息渠道名称;1：阿里云
        /// </summary>
        [Field("短息渠道名称")]
        public string ChannelName { get; set; }

        /// <summary>
        /// 短息签名名称
        /// </summary>
        [Field("短息签名名称")]
        public string SignName { get; set; }

        /// <summary>
        /// 短息模板id
        /// </summary>
        [Field("短息模板id")]
        public string TemplateCode { get; set; }

        /// <summary>
        /// 短息模板变量值;短信平台模板参数json字符串
        /// </summary>
        [Field("短息模板变量值")]
        public string TemplateParam { get; set; }

        /// <summary>
        /// 短息内容
        /// </summary>
        [Field("短息内容")]
        public string Content { get; set; }

        /// <summary>
        /// 发送方式;1：单发，2：群发
        /// </summary>
        [Field("发送方式")]
        public int SendType { get; set; }

        /// <summary>
        /// 接收手机号码;不同的手机号码直接通过,连接
        /// </summary>
        [Field("接收手机号码")]
        public string PhoneNumbers { get; set; }

        /// <summary>
        /// 发送状态;1：待发送，2：已发送，3：发送失败
        /// </summary>
        [Field("发送状态")]
        public int SendState { get; set; }

        /// <summary>
        /// 提交时间;我方提交短信平台时间
        /// </summary>
        [Field("提交时间")]
        public DateTime SubmitTime { get; set; }

        /// <summary>
        /// 发送回执ID
        /// </summary>
        [Field("发送回执ID")]
        public string BizId { get; set; }

        /// <summary>
        /// 请求id
        /// </summary>
        [Field("请求id")]
        public string RequestId { get; set; }

        /// <summary>
        /// 发送结果备注
        /// </summary>
        [Field("发送结果备注")]
        public string SendRemark { get; set; }

    }
}
