//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HS.Message.Share.Attributes;

namespace HS.Message.Model
{


    /// <summary>
    /// 短息消息详情
    /// </summary>
    public partial class MSmsMessageDetails: MBaseModel
    {
        /// <summary>
        /// 短信消息主id
        /// </summary>
        [Field("短信消息主id")]
        public string SmsMessageId { get; set; }

        /// <summary>
        /// 短息渠道编号;1：阿里云
        /// </summary>
        [Field("短息渠道编号")]
        public int ChannelCode { get; set; }

        /// <summary>
        /// 短息渠道名称;1：阿里云
        /// </summary>
        [Field("短息渠道名称")]
        public string ChannelName { get; set; }

        /// <summary>
        /// 短息内容
        /// </summary>
        [Field("短息内容")]
        public string Content { get; set; }

        /// <summary>
        /// 接收手机号码;不同的手机号码直接通过,连接
        /// </summary>
        [Field("接收手机号码")]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// 已发送次数
        /// </summary>
        [Field("已发送次数")]
        public int HasSendNum { get; set; }

        /// <summary>
        /// 发送状态;1：发送锁定（代表正在发送），2：已发送 （代表已经将短信发送到运营商），3：发送成功（运营商返回成功），4：发送失败（运营商返回失败）
        /// </summary>
        [Field("发送状态")]
        public int SendState { get; set; }

        /// <summary>
        /// 运营商状态编码
        /// </summary>
        [Field("运营商状态编码")]
        public string OperatorStateCode { get; set; }

        /// <summary>
        /// 锁定时间
        /// </summary>
        [Field("锁定时间")]
        public DateTime LockTime { get; set; }

        /// <summary>
        /// 提交时间;我方提交短信平台时间
        /// </summary>
        [Field("提交时间")]
        public DateTime SubmitTime { get; set; }

        /// <summary>
        /// 接收时间;用户查看时间
        /// </summary>
        [Field("接收时间")]
        public DateTime ReceiveTime { get; set; }

        /// <summary>
        /// 上一次发送时间
        /// </summary>
        [Field("上一次发送时间")]
        public DateTime LastSendTime { get; set; }

        /// <summary>
        /// 发送回执ID
        /// </summary>
        [Field("发送回执ID")]
        public string BizId { get; set; }

        /// <summary>
        /// 请求id
        /// </summary>
        [Field("请求id")]
        public string RequestId { get; set; }

        /// <summary>
        /// 查询锁定状态;1：锁定，2：未锁定
        /// </summary>
        [Field("查询锁定状态")]
        public int QueryLockState { get; set; }

        /// <summary>
        /// 查询锁定时间
        /// </summary>
        [Field("查询锁定时间")]
        public DateTime QueryLockTime { get; set; }
    }
}
