//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HS.Message.Share.Attributes;

namespace HS.Message.Model
{


    /// <summary>
    // SmsMessage数据模型
    /// </summary>
    public partial class MSmsMessage: MBaseModel
    {
        
        /// <summary>
        // 乐观锁
        /// </summary>
        private int? _REVISION;
        
        /// <summary>
        // id
        /// </summary>
        private int _id;
        
        /// <summary>
        // 逻辑id
        /// </summary>
        private string _logical_id;
        
        /// <summary>
        // 消息id
        /// </summary>
        private string _message_id;
        
        /// <summary>
        // 消息接收人id
        /// </summary>
        private string _receiver_id;
        
        /// <summary>
        // 短息渠道编号;1：阿里云
        /// </summary>
        private int? _channel_code;
        
        /// <summary>
        // 短息渠道名称;1：阿里云
        /// </summary>
        private string _channel_name;
        
        /// <summary>
        // 短息签名名称
        /// </summary>
        private string _sign_name;
        
        /// <summary>
        // 短息模板id
        /// </summary>
        private string _template_code;
        
        /// <summary>
        // 短息模板变量值;短信平台模板参数json字符串
        /// </summary>
        private string _template_param;
        
        /// <summary>
        // 短息内容
        /// </summary>
        private string _content;
        
        /// <summary>
        // 发送方式;1：单发，2：群发
        /// </summary>
        private int _send_type;
        
        /// <summary>
        // 接收手机号码;不同的手机号码直接通过,连接
        /// </summary>
        private string _phone_numbers;
        
        /// <summary>
        // 发送状态;1：待发送，2：已发送，3：发送失败
        /// </summary>
        private int _send_state;
        
        /// <summary>
        // 提交时间;我方提交短信平台时间
        /// </summary>
        private System.DateTime _submit_time;
        
        /// <summary>
        // 发送回执ID
        /// </summary>
        private string _biz_id;
        
        /// <summary>
        // 请求id
        /// </summary>
        private string _request_id;
        
        /// <summary>
        // 发送结果备注
        /// </summary>
        private string _send_remark;
        
        /// <summary>
        // 创建人Id
        /// </summary>
        private string _created_by_id;
        
        /// <summary>
        // 创建人姓名
        /// </summary>
        private string _created_by_name;
        
        /// <summary>
        // 创建时间
        /// </summary>
        private System.DateTime _created_time;
        
        /// <summary>
        // 更新人Id
        /// </summary>
        private string _updated_by_id;
        
        /// <summary>
        // 更新人姓名
        /// </summary>
        private string _updated_by_name;
        
        /// <summary>
        // 更新时间
        /// </summary>
        private System.DateTime _updated_time;
        
        /// <summary>
        /// 乐观锁
        /// </summary>
        [FieldAttribute("乐观锁")]
        public int? REVISION
        {
            get
            {
                return this._REVISION;
            }
            set
            {
                this._REVISION = value;
            }
        }
        
        /// <summary>
        /// id
        /// </summary>
        [FieldAttribute("id")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        /// <summary>
        /// 逻辑id
        /// </summary>
        [FieldAttribute("逻辑id")]
        public string logical_id
        {
            get
            {
                return this._logical_id;
            }
            set
            {
                this._logical_id = value;
            }
        }
        
        /// <summary>
        /// 消息id
        /// </summary>
        [FieldAttribute("消息id")]
        public string message_id
        {
            get
            {
                return this._message_id;
            }
            set
            {
                this._message_id = value;
            }
        }
        
        /// <summary>
        /// 消息接收人id
        /// </summary>
        [FieldAttribute("消息接收人id")]
        public string receiver_id
        {
            get
            {
                return this._receiver_id;
            }
            set
            {
                this._receiver_id = value;
            }
        }
        
        /// <summary>
        /// 短息渠道编号;1：阿里云
        /// </summary>
        [FieldAttribute("短息渠道编号;1：阿里云")]
        public int? channel_code
        {
            get
            {
                return this._channel_code;
            }
            set
            {
                this._channel_code = value;
            }
        }
        
        /// <summary>
        /// 短息渠道名称;1：阿里云
        /// </summary>
        [FieldAttribute("短息渠道名称;1：阿里云")]
        public string channel_name
        {
            get
            {
                return this._channel_name;
            }
            set
            {
                this._channel_name = value;
            }
        }
        
        /// <summary>
        /// 短息签名名称
        /// </summary>
        [FieldAttribute("短息签名名称")]
        public string sign_name
        {
            get
            {
                return this._sign_name;
            }
            set
            {
                this._sign_name = value;
            }
        }
        
        /// <summary>
        /// 短息模板id
        /// </summary>
        [FieldAttribute("短息模板id")]
        public string template_code
        {
            get
            {
                return this._template_code;
            }
            set
            {
                this._template_code = value;
            }
        }
        
        /// <summary>
        /// 短息模板变量值;短信平台模板参数json字符串
        /// </summary>
        [FieldAttribute("短息模板变量值;短信平台模板参数json字符串")]
        public string template_param
        {
            get
            {
                return this._template_param;
            }
            set
            {
                this._template_param = value;
            }
        }
        
        /// <summary>
        /// 短息内容
        /// </summary>
        [FieldAttribute("短息内容")]
        public string content
        {
            get
            {
                return this._content;
            }
            set
            {
                this._content = value;
            }
        }
        
        /// <summary>
        /// 发送方式;1：单发，2：群发
        /// </summary>
        [FieldAttribute("发送方式;1：单发，2：群发")]
        public int send_type
        {
            get
            {
                return this._send_type;
            }
            set
            {
                this._send_type = value;
            }
        }
        
        /// <summary>
        /// 接收手机号码;不同的手机号码直接通过,连接
        /// </summary>
        [FieldAttribute("接收手机号码;不同的手机号码直接通过,连接")]
        public string phone_numbers
        {
            get
            {
                return this._phone_numbers;
            }
            set
            {
                this._phone_numbers = value;
            }
        }
        
        /// <summary>
        /// 发送状态;1：待发送，2：已发送，3：发送失败
        /// </summary>
        [FieldAttribute("发送状态;1：待发送，2：已发送，3：发送失败")]
        public int send_state
        {
            get
            {
                return this._send_state;
            }
            set
            {
                this._send_state = value;
            }
        }
        
        /// <summary>
        /// 提交时间;我方提交短信平台时间
        /// </summary>
        [FieldAttribute("提交时间;我方提交短信平台时间")]
        public System.DateTime submit_time
        {
            get
            {
                return this._submit_time;
            }
            set
            {
                this._submit_time = value;
            }
        }
        
        /// <summary>
        /// 发送回执ID
        /// </summary>
        [FieldAttribute("发送回执ID")]
        public string biz_id
        {
            get
            {
                return this._biz_id;
            }
            set
            {
                this._biz_id = value;
            }
        }
        
        /// <summary>
        /// 请求id
        /// </summary>
        [FieldAttribute("请求id")]
        public string request_id
        {
            get
            {
                return this._request_id;
            }
            set
            {
                this._request_id = value;
            }
        }
        
        /// <summary>
        /// 发送结果备注
        /// </summary>
        [FieldAttribute("发送结果备注")]
        public string send_remark
        {
            get
            {
                return this._send_remark;
            }
            set
            {
                this._send_remark = value;
            }
        }
        
        /// <summary>
        /// 创建人Id
        /// </summary>
        [FieldAttribute("创建人Id")]
        public string created_by_id
        {
            get
            {
                return this._created_by_id;
            }
            set
            {
                this._created_by_id = value;
            }
        }
        
        /// <summary>
        /// 创建人姓名
        /// </summary>
        [FieldAttribute("创建人姓名")]
        public string created_by_name
        {
            get
            {
                return this._created_by_name;
            }
            set
            {
                this._created_by_name = value;
            }
        }
        
        /// <summary>
        /// 创建时间
        /// </summary>
        [FieldAttribute("创建时间")]
        public System.DateTime created_time
        {
            get
            {
                return this._created_time;
            }
            set
            {
                this._created_time = value;
            }
        }
        
        /// <summary>
        /// 更新人Id
        /// </summary>
        [FieldAttribute("更新人Id")]
        public string updated_by_id
        {
            get
            {
                return this._updated_by_id;
            }
            set
            {
                this._updated_by_id = value;
            }
        }
        
        /// <summary>
        /// 更新人姓名
        /// </summary>
        [FieldAttribute("更新人姓名")]
        public string updated_by_name
        {
            get
            {
                return this._updated_by_name;
            }
            set
            {
                this._updated_by_name = value;
            }
        }
        
        /// <summary>
        /// 更新时间
        /// </summary>
        [FieldAttribute("更新时间")]
        public System.DateTime updated_time
        {
            get
            {
                return this._updated_time;
            }
            set
            {
                this._updated_time = value;
            }
        }
    }
}
